# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'NetDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NetDemo
  pod 'Alamofire', '~> 5.4'

end
